import { Link } from 'react-router-dom';
import { ArrowRight, Check, ExternalLink } from 'lucide-react';
import PublicHeader from '../../components/layout/PublicHeader';
import PublicFooter from '../../components/layout/PublicFooter';
import Reveal from '../../components/ui/Reveal';
import { PRODUCTS } from '../../lib/products';

export default function Products() {
  return <div className="public-glass-page min-h-screen bg-white text-slate-950"><PublicHeader /><main className="pt-20">
    <section className="premium-page-hero py-28 sm:py-36"><div className="corporate-grid absolute inset-0 opacity-30" aria-hidden="true" /><div className="absolute -left-24 top-10 h-80 w-80 rounded-full bg-amber-300/20 blur-[100px]" /><div className="absolute right-0 top-0 h-96 w-96 rounded-full bg-sky-400/20 blur-[120px]" /><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.24em] text-sky-800">Product portfolio</p><div className="mt-7 grid gap-10 lg:grid-cols-[1fr_0.7fr] lg:items-end"><h1 className="max-w-4xl font-display text-5xl font-semibold leading-[1.02] tracking-[-0.055em] text-[#102d48] sm:text-7xl">Focused software for <span className="bg-gradient-to-r from-sky-700 to-amber-500 bg-clip-text text-transparent">real operating challenges.</span></h1><p className="max-w-xl text-lg leading-8 text-slate-600 lg:justify-self-end">We build, operate and continuously improve our own platforms. Each product has a clear audience, an honest status and a direct path to value.</p></div></div></section>
    <section className="bg-gradient-to-b from-slate-50 via-white to-blue-50/50 py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="space-y-10">{PRODUCTS.map(product => { const live = product.status === 'live'; return <Reveal key={product.key} className="grid overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-[0_30px_90px_-50px_rgba(15,23,42,0.55)] transition-all duration-300 hover:-translate-y-1 hover:border-sky-300 lg:grid-cols-[0.72fr_1.28fr]"><div className={`relative flex min-h-72 flex-col justify-between overflow-hidden bg-gradient-to-br ${product.gradient} p-8 text-white sm:p-10`}><div className="absolute -right-16 -top-16 h-52 w-52 rounded-full border border-white/20" aria-hidden="true" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/35 to-transparent" /><product.icon className="relative h-12 w-12" /><div className="relative mt-16"><p className="text-xs font-bold uppercase tracking-[0.18em] text-white/70">{live ? 'Available now' : 'In development'}</p><h2 className="mt-3 text-4xl font-bold tracking-tight">{product.name}</h2><p className="mt-2 text-sm text-white/80">{product.tagline}</p></div></div><div className="p-8 sm:p-10 lg:p-12"><div className="grid gap-8 md:grid-cols-[1fr_0.85fr]"><div><p className="text-base leading-7 text-slate-600">{product.description}</p><div className="mt-8">{live && product.href && product.external ? <a href={product.href} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-sky-500/20">Open product <ExternalLink className="h-4 w-4" /></a> : live && product.href ? <Link to={product.href} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-sky-500/20">Explore product <ArrowRight className="h-4 w-4" /></Link> : <Link to="/contact" className="inline-flex items-center gap-2 text-sm font-bold text-sky-700 hover:text-sky-800">Ask about the roadmap <ArrowRight className="h-4 w-4" /></Link>}</div></div><ul className="space-y-3 border-t border-slate-200 pt-6 md:border-l md:border-t-0 md:pl-8 md:pt-0">{product.features.map(feature => <li key={feature} className="flex gap-3 text-sm leading-6 text-slate-700"><Check className="mt-1 h-4 w-4 shrink-0 text-cyan-500" />{feature}</li>)}</ul></div></div></Reveal>; })}</div></div></section>
    <section className="border-y border-sky-100 bg-gradient-to-r from-white via-sky-50/70 to-amber-50/50 py-20"><div className="mx-auto flex max-w-7xl flex-col gap-7 px-4 sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><p className="corporate-eyebrow">Need a tailored solution?</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-tight text-[#102d48]">Our delivery team can build around your operation.</h2></div><Link to="/book-online" className="luxury-button-primary shrink-0 gap-2">Start a project <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main><PublicFooter /></div>;
}
