import { Link } from 'react-router-dom';
import { ArrowRight, Check, ExternalLink } from 'lucide-react';
import PublicHeader from '../../components/layout/PublicHeader';
import PublicFooter from '../../components/layout/PublicFooter';
import Reveal from '../../components/ui/Reveal';
import { PRODUCTS } from '../../lib/products';

export default function Products() {
  return <div className="min-h-screen bg-white text-slate-950"><PublicHeader /><main className="pt-20">
    <section className="relative overflow-hidden bg-slate-950 py-20 sm:py-28"><div className="corporate-grid absolute inset-0 opacity-50" aria-hidden="true" /><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-sky-300">Product portfolio</p><div className="mt-5 grid gap-8 lg:grid-cols-[1fr_0.7fr] lg:items-end"><h1 className="max-w-4xl text-4xl font-bold leading-[1.05] tracking-[-0.04em] text-white sm:text-6xl">Focused software for real operating challenges.</h1><p className="max-w-xl text-base leading-7 text-slate-300 lg:justify-self-end">We build, operate and continuously improve our own platforms. Each product has a clear audience, an honest status and a direct path to value.</p></div></div></section>
    <section className="py-16 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="space-y-8">{PRODUCTS.map(product => { const live = product.status === 'live'; return <Reveal key={product.key} className="grid overflow-hidden border border-slate-200 bg-white lg:grid-cols-[0.72fr_1.28fr]"><div className={`relative flex min-h-64 flex-col justify-between overflow-hidden bg-gradient-to-br ${product.gradient} p-8 text-white sm:p-10`}><div className="absolute -right-16 -top-16 h-52 w-52 rounded-full border border-white/20" aria-hidden="true" /><product.icon className="relative h-10 w-10" /><div className="relative mt-16"><p className="text-xs font-bold uppercase tracking-[0.18em] text-white/70">{live ? 'Available now' : 'In development'}</p><h2 className="mt-3 text-3xl font-bold tracking-tight">{product.name}</h2><p className="mt-2 text-sm text-white/80">{product.tagline}</p></div></div><div className="p-8 sm:p-10 lg:p-12"><div className="grid gap-8 md:grid-cols-[1fr_0.85fr]"><div><p className="text-base leading-7 text-slate-600">{product.description}</p><div className="mt-8">{live && product.href && product.external ? <a href={product.href} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-md bg-slate-950 px-5 py-3 text-sm font-bold text-white hover:bg-sky-700">Open product <ExternalLink className="h-4 w-4" /></a> : live && product.href ? <Link to={product.href} className="inline-flex items-center gap-2 rounded-md bg-slate-950 px-5 py-3 text-sm font-bold text-white hover:bg-sky-700">Explore product <ArrowRight className="h-4 w-4" /></Link> : <Link to="/contact" className="inline-flex items-center gap-2 text-sm font-bold text-sky-700 hover:text-sky-800">Ask about the roadmap <ArrowRight className="h-4 w-4" /></Link>}</div></div><ul className="space-y-3 border-t border-slate-200 pt-6 md:border-l md:border-t-0 md:pl-8 md:pt-0">{product.features.map(feature => <li key={feature} className="flex gap-3 text-sm leading-6 text-slate-700"><Check className="mt-1 h-4 w-4 shrink-0 text-sky-700" />{feature}</li>)}</ul></div></div></Reveal>; })}</div></div></section>
    <section className="border-y border-slate-200 bg-slate-50 py-16"><div className="mx-auto flex max-w-7xl flex-col gap-7 px-4 sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><p className="corporate-eyebrow">Need a tailored solution?</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Our delivery team can build around your operation.</h2></div><Link to="/book-online" className="inline-flex shrink-0 items-center gap-2 rounded-md bg-sky-700 px-6 py-3.5 text-sm font-bold text-white hover:bg-sky-800">Start a project <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main><PublicFooter /></div>;
}
